name: Chuckie Egg

on:
  push:
    tags:
      - 'v*'   # e.g. v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build tools
        run: |
          apt update
          apt install build-essential git -y

      - name: Checkout beebasm
        uses: actions/checkout@v4
        with:
          repository: stardot/beebasm
          ref: v1.10
          path: beebasm

      - name: Build beebasm
        run: |
          cd beebasm/src
          make code
          cp ../beebasm /usr/local/bin

      - name: Build Chuckie
        run: |
          make

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: chuckie-egg
          path: |
            *.ssd

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: chuckie-egg
          path: dist

      - name: Create release zip
        run: |
          ls -R dist
          zip -r chuckie-egg-${{ github.ref_name }}.zip dist/*

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            chuckie-egg-${{ github.ref_name }}.zip
